language: cpp

branches:
  only:
    - test

os:
  - linux

install:
 - wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
 - chmod +x qt-opensource-linux-x64-5.7.0.run
 - ./qt-opensource-linux-x64-5.7.0.run
 - sudo apt-get install build-essential libfontconfig1 mesa-common-dev
 - sudo apt-get install libglu1-mesa-dev -y

script:
 - lrelease res/lang/en.ts
 - qmake apkstudio.pro CONFIG+=release
 - make
