language: cpp

branches:
  only:
    - ci-test-release

os:
  - linux

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - lrelease res/lang/en.ts
  - qmake apkstudio.pro CONFIG+=release
  - make

  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage

  - mkdir apkstudio-latest-release
  - cd apkstudio-latest-release
  - cp ../apkstudio .

  - ../linuxdeployqt*.AppImage apkstudio -bundle-non-qt-libs -no-translations -verbose=2
  - ls -al
# removing doc folder, apprun shortcut and .DirIcon 
  - rm -rf doc AppRun .DirIcon
# removing extra libraries
  - cd  lib && mv libQt5Core.so.5 libQt5Gui.so.5 libQt5Widgets.so.5 libicu* .. && rm -r * && mv ../libQ* ../libi* . && cd ..
#
  - rm -rf plugins/imageformats/ plugins/platforminputcontexts/ plugins/xcbglintegrations/

  - cd ..
  - tar -zvcf apkstudio-latest-release.tar.gz apkstudio-latest-release

after_script:
  - curl --upload-file ./apkstudio-latest-release.tar.gz https://transfer.sh/apkstudio-latest-release-git.$(git rev-parse --short HEAD)-linux_x86_64.tar.gz