os:
  - linux

language: cpp

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt55
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-4.9 qt55base qt55tools
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
 # No more needed
 # - lsb_release -s -d
 # - g++ --version
 # No more needed
 - source /opt/qt55/bin/qt55-env.sh
 - qmake apkstudio.pro CONFIG+=release
 - make
