language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ppa:beineri/opt-qt-5.12.3-xenial
          packages:
            - libgl1-mesa-dev
            - qt512base
    - os: osx
      osx_image: xcode9

before_install: |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew update
    fi

install: |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      source /opt/qt*/bin/qt*-env.sh
    fi
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew install qt
      brew link --force qt
    fi

script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then chmod +x $TRAVIS_BUILD_DIR/build/linux.sh; $TRAVIS_BUILD_DIR/build/linux.sh; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then chmod +x $TRAVIS_BUILD_DIR/build/osx.sh; $TRAVIS_BUILD_DIR/build/osx.sh; fi

deploy:
  provider: releases
  api_key:
    secure: pjGl0U3TeHDzfHeW+VmrPQFdQtbLsIlV0niwSfGIUGQ+WD+LA4VDJNhu5ctUpR4yWVZWWUtBoj7M9g2D2h+7wi7MkFFJqIgxz41Fc41W/93WD2sC6I/5Y3AsNk4xGf5WuDYOB64lKBrc5uGn4HT696ixSkG3HEd/0WLd56BS0VM=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    tags: true
