branches:
  only:
    - app-veyor-test

install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - lrelease res\lang\en.ts
  - qmake apkstudio.pro
  - mingw32-make
after_build:
  - windeployqt release/apkstudio.exe
#  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\apkstudio-*.exe
  - path: release
    type: zip
